apiVersion: v1
name: Blackr # This value was modified by the initial-setup python script
description: A Helm chart for deploying Blackr-frontend. # This value was modified by the initial-setup python script
version: 1.0
